function [fitresult, gof] = FourierFit(stim, AvgFr)
%CREATEFIT(STIM,AVGFR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : stim
%      Y Output: AvgFr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Jul-2019 16:54:01


%% Fit: 'Fourier fit 1'.
[xData, yData] = prepareCurveData( stim, AvgFr );

% Set up fittype and options.
ft = fittype( 'fourier1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 2.0943951023932];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fourier fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'AvgFr vs. stim', 'untitled fit 1', 'Location', 'NorthEast' );

title TuningCurveRandomDelayTask
% Label axes
xlabel stimuli
ylabel AvgFr
grid on


