function [fitresult, gof] = GaussFit(stim, AvgFR)
%CREATEFIT(STIM,AVGFR)
%  Create a fit.
%
%  Data for 'Gaussion fit' fit:
%      X Input : stim
%      Y Output: AvgFR
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Jul-2019 16:11:05


%% Fit: 'Gaussion fit'.
[xData, yData] = prepareCurveData( stim, AvgFR );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [2.40802675585284 3 0.833621727617423];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Gaussion fit' );
h = plot( fitresult, xData, yData );
legend( h, 'AvgFR vs. stim', 'Gaussion fit', 'Location', 'NorthEast' );
% Title
title('TunningCurveFixedDelayTask')
% Label axes
xlabel stimuli
ylabel AvgFR
grid on


